# Change these first
owner: belo-app # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: belo
    url: https://beta.belo.app/health

status-website:
  cname: status.belo.app
  # baseUrl: /status
  logoUrl: https://www.belo.app/images/belo.svg
  name: belo
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

